### PR TITLE
fix: show popup if ledger disconnected

### LINKED ISSUE #2251: ️🛠 - Fix unresponsive button upon ledger profile creation flow
### Task description

Upon restoring/creating a profile the following button becomes unresponsive if the ledger :

image

Steps to reproduce:
1) Create a hardware profile
2) Disconnect ledger profile on the FinishOnboardingView.svelte page
3) The user can click on next, but nothing happens.

### Requirements

What solution should be implemented?

### PR DESCRIPTION
**Pull request by Tuditi**
## Summary

Closes: #2251 

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by nicole-obrien** [comment]
Do you not want to use the new async popup for this?

File: packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte [hunk 1]
```diff
@@ -22,16 +23,13 @@
...
-        }
-    }
-
-    async function _continue(): Promise<void> {
+    async function onContinueClick(): Promise<void> {
         try {
+            if ($isOnboardingLedgerProfile) {
+                await checkOrConnectLedgerAsync(appName)
+            } else {
+                await checkOrUnlockStrongholdAsync()
```
Comment (nicole-obrien) [inline packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte]: We shouldn't need this because stronghold is already unlocked and we have not set a timer to lock it yet?

File: packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte [hunk 2]
```diff
@@ -22,16 +23,13 @@
...
+            }
             await completeOnboardingProcess()
```
Comment (nicole-obrien) [inline packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte:30]: code is not reaching this point after unlocking ledger through the popup

File: packages/shared/src/lib/core/ledger/actions/checkOrConnectLedger.ts [hunk 3]
```diff
@@ -28,15 +28,19 @@ export function checkOrConnectLedger(
...
             return callback()
         } else {
-            openPopup({
-                id: PopupId.ConnectLedger,
-                hideClose: true,
-                props: {
-                    ledgerAppName,
-                    onContinue: _callback,
-                    onCancel,
+            openPopup(
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/ledger/actions/checkOrConnectLedger.ts]: not using this in onboarding so no need to edit

**Review by nicole-obrien — CHANGES_REQUESTED** [review]

File: packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte (hunk 1 above)
Comment (Tuditi) [reply packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte]: True, I'll remove it, since the password clear interval is set in `login()`

Comment (Tuditi) [reply packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte]: We have similar logic in `BalanceFinderView`, so I removed it there as well.

File: packages/shared/src/lib/core/ledger/actions/checkOrConnectLedgerAsync.ts [hunk 4]
```diff
@@ -20,7 +20,7 @@ export function checkOrConnectLedgerAsync(
                 hideClose: true,
                 props: {
                     ledgerAppName,
-                    onSuccess: resolve,
+                    onContinue: resolve,
```
Comment (MarkNerdi) [inline packages/shared/src/lib/core/ledger/actions/checkOrConnectLedgerAsync.ts]: lets make the prop the same for `ConnectLedgerPopup` and `UnlockStrongholdPopup`. 
I think `onSuccess` is the better of both

**Review by nicole-obrien — APPROVED** [review]
