### PR TITLE
fix: fix success popup

### LINKED ISSUE #1601: ️🛠 - Only show SuccessPopup on dapp interaction
### Task description

_No response_

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Tuditi — CHANGES_REQUESTED** [review]
Things left to fix:

- Doesn't close the verify pop-up for Ledger after signing a message or rejecting it on the device.
- Add resetSendParameters() after transaction has been sent
- Runtime error by unhandled error in ledger.class.ts:115
image

If I click outside of the sendTransaction Pop-up while it's still in the busy state, the callback rejects, but we still show the success pop-up.

image

File: packages/shared/src/lib/core/wallet/actions/send/sendTransactionFromEvm.ts [hunk 1]
```diff
@@ -27,6 +28,7 @@ export async function sendTransactionFromEvm(
     return new Promise((resolve, reject) => {
         checkActiveProfileAuth(
             async () => {
+                modifyPopupState({ preventClose: true })
```
Comment (Tuditi) [inline packages/shared/src/lib/core/wallet/actions/send/sendTransactionFromEvm.ts]: This is problematic for ledger devices, because it doesn't allow to open the VerifyLedgerTransaction popup anymore.

**Review by Tuditi — CHANGES_REQUESTED** [review]

**Review by Tuditi — APPROVED** [review]
LGTM!
