### PR TITLE
fix: bind error on ui kit inputs

### LINKED ISSUE #1095: 🐞 - Wrong Password and Field disappears
### Task description

Somehow I managed to write the wrong password. And when I tried to change/correct the password the popup disappeard. But I am not sure what went wrong because it happened 2 times but the third time it worked flawlessly…

image

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/components/popup/popups/CreateAccountPopup.svelte [hunk 1]
```diff
@@ -86,7 +86,7 @@
     <div class="flex flex-col space-y-5">
         <div class="flex flex-col gap-2">
             <Text type="body1">{localize('general.name')}</Text>
-            <Input bind:value={accountName} label={localize('general.accountName')} disabled={isBusy} {error} />
+            <Input bind:value={accountName} label={localize('general.accountName')} disabled={isBusy} bind:error />
```
Comment (Tuditi) [inline packages/desktop/components/popup/popups/CreateAccountPopup.svelte:87]: This uses `handleError`. Remove it and replace `err.error` with `err.message` just like in `CustomiseAccountPopup`.

**Review by Tuditi — CHANGES_REQUESTED** [review]
One change requested.

**Review by Tuditi — APPROVED** [review]
LGTM! :cherry_blossom:
