### PR TITLE
feat: add hidden balance change and fix l2 activity when sending from l1 l2

### LINKED ISSUE #614: ️🛠 - Add hidden balance change and fix L2 activity when sending from L1 -> L2
### Task description

Currently there are three separate activities produced when unwrapping a token from L2->L1:
1. A transaction that indicates `0` for the `value` field but the transfer parameters are embedded in the `data` field 
2. Receipt of unwrapped funds on L1 from the ShimmerEVM Testnet
3. Balance change event for L2 address 

Screenshot from 2023-09-06 11-13-42

### Requirements

- [ ] Remove 3 entirely by adding a hidden balance change to the persisted store
- [ ] Adjust 1 so that the address is the correct L1 address and the amount is the amount sent / unwrapped

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/layer-2/interfaces/isc-send-method-inputs.interface.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
+export interface IscSendMethodInputs {
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/interfaces/isc-send-method-inputs.interface.ts:4]: All of these interfaces / types are in `layer-2-send-<blank>.interface.ts` files, would be worth checking those out. They're used in unwrapping

**Review by maxwellmattryan — CHANGES_REQUESTED** [review]
One requested change :pray:

**Review by maxwellmattryan — APPROVED** [review]
LGTM :cherry_blossom:
