### PR TITLE
fix: add validation if wallet supports any chain

### LINKED ISSUE #1663: 🐞 - Network warning doesn't show properly when connecting to ShimmerSea with Wallet Connect
### Version

0.1.3

### Description

The following drawer is shown when logging in into a **testnet** profile:

image

### Expected behaviour

We show that they need a profile for the ShimmerEVM.

### Actual behaviour

There is missing information on the connect dapp screen

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Have Bloom open with only 1 testnet profile
2. Open https://shimmersea.finance
3. Connect to a deep link
4. Log in
5. Go through the behavior

### Crash Status

None of the above

### Error Messages

None

### Error Logs

```shell
None
```

### Profile Type

Software (Stronghold)

### Operating System

Linux

### Diagnostics

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/dashboard/drawers/dapp-config/views/ConnectionRequestDrawer.svelte [hunk 1]
```diff
@@ -27,9 +27,17 @@
...
-    $: fulfillsRequirements = unsupportedMethods.length === 0 && unsupportedNetworks.length === 0
+    $: supportedNetworks = $sessionProposal
+        ? getSupportedNetworks($sessionProposal?.params.requiredNamespaces, $sessionProposal?.params.optionalNamespaces)
+        : []
+    $: unsupportedRequiredNetworks = $sessionProposal
+        ? getUnsupportedRequiredNetworks($sessionProposal?.params.requiredNamespaces)
+        : []
+    $: isSupportedOnOtherProfiles = $sessionProposal
+        ? areNetworksSupportedOnOtherProfiles(unsupportedRequiredNetworks)
+        : false
```
Comment (Tuditi) [inline packages/desktop/views/dashboard/drawers/dapp-config/views/ConnectionRequestDrawer.svelte]: It's better to move the `$sessionProposal` checks into the respective functions to simplify the arguments for l.31 and for cleaner code.

**Review by Tuditi — CHANGES_REQUESTED** [review]
Works fine, one minor remark.

**Review by Tuditi — APPROVED** [review]
LGTM! :blossom:
