### PR TITLE
fix: only address gets inserted if contact is selected on recipientinput

### LINKED ISSUE #405: ️🛠 - Inconsistent `RecipientInput` behavior when clicking other inputs
### Task description

When in the `NetworkRecipientPopup`, entering a recipient for one of the inputs then choosing the other card will result in different behavior when doing it for both cards. The input for the testnet shows the input correctly when going back to it, but the ShimmerEVM testnet input shows the input incorrectly (shows address text) when going back to it.

Screenshot from 2023-08-08 15-38-18
Screenshot from 2023-08-08 15-38-22

### Requirements

_TBD_

### LINKED ISSUE #443: ️🛠 - Fix send button on contact address
### Task description

By using the send button on the contact book, the recipient isnt correclty shown in the `SelectRecipient` popup. For this we need to pass in the network id into the sendflow as well

### Requirements

- [ ] pass in the network id into the sendflow

### LINKED ISSUE #469: ️🛠 - Only address gets inserted if contact is selected on RecipientInput
### Task description

If the user selects a contact in the `SelectRecipientView` and goes forth and back, the field is prefilled only with the address instead of the contact. 
The reason is because in `RecipientInput`->`getSubjectFromAddress` we dont pass in the networkId

Same goes for Account.

### Requirements

- [ ] Pass in `networkId` into `RecipientInput`
- [ ] Fix initial value for recipient for L2 addresses

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/profile/actions/active-accounts/findActiveAccountWithAddress.ts [hunk 1]
```diff
@@ -1,16 +1,23 @@
...
-    return accounts.find((account) => account.depositAddress === address)
+
+    return accounts.find((account) => {
+        if (isStardustNetwork(networkId)) {
+            return account.depositAddress === address
+        } else {
+            const coinType = getChainConfiguration(networkId)?.coinType
+            return coinType !== undefined && account.evmAddresses[coinType] === address
+        }
+    })
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/profile/actions/active-accounts/findActiveAccountWithAddress.ts]: Not necessarily but probably would be good to have a util function (or multiple) for getting an address on an account, could be defaulted to the selected account. A function like this would be really useful throughout the entire app

**Review by maxwellmattryan — DISMISSED** [review]
App is looking good! Request a change but entirely optional :+1:

**Review by maxwellmattryan — APPROVED** [review]
LGTM :cherry_blossom:
