### PR TITLE
fix: nft description gets cut on the transaction details popup

### LINKED ISSUE #1074: 🐞 - NFT description gets cut on the transaction details popup
### Task description

image

### Requirements

_No response_

### LINKED ISSUE #1093: 🐞 - Transaction Hash of Ledger transaction not displayed fully, so check not possible
### Task description

image

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/components/molecules/activity-info/AliasActivityInformation.svelte [hunk 1]
```diff
@@ -11,14 +11,17 @@
...
         },
         {
             key: localize('general.governorAddress'),
             value: activity.governorAddress,
+            truncate: true,
         },
         {
             key: localize('general.stateControllerAddress'),
             value: activity.stateControllerAddress,
+            truncate: true,
```
Comment (Tuditi) [inline packages/shared/src/components/molecules/activity-info/AliasActivityInformation.svelte]: These should be copyable.

File: packages/shared/src/components/molecules/activity-info/NftMetadataInformation.svelte [hunk 2]
```diff
@@ -30,8 +30,6 @@
             {
                 key: localize('general.uri'),
                 value: metadata.uri,
-                copyable: true,
```
Comment (Tuditi) [inline packages/shared/src/components/molecules/activity-info/NftMetadataInformation.svelte:33]: Why is the URL not copyable anymore?

**Review by Tuditi — CHANGES_REQUESTED** [review]
Some minor changes requested, but fixes the issue.

**Review by Tuditi — APPROVED** [review]
LGTM! :fire:
