### PR TITLE
ui: fix tabsection height

### LINKED ISSUE #736: ️🛠 - Fix TabSection height
### Task description

_No response_

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte [hunk 1]
```diff
@@ -6,17 +6,22 @@
...
+            <Pane classes="flex flex-col flex-grow border border-solid border-gray-100">
+                <TabSection />
+            </Pane>
         {/key}
     </wallet-container>
 {/if}
+
+<style lang="scss">
+    wallet-container {
+        height: calc(100vh - 39px);
```
Comment (nicole-obrien) [inline packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte]: What is this buffer?

File: packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte [hunk 2]
```diff
@@ -27,8 +27,8 @@
     }
 </script>
 
-<div class="h-full flex flex-auto flex-col flex-grow shrink-0">
-    <div class="header-row">
+<div class="flex flex-col flex-grow" style="height: calc(100% - 68px);">
```
Comment (nicole-obrien) [inline packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte]: What is this buffer?

**Review by nicole-obrien — DISMISSED** [review]
I don't think we should be having random pixel buffers like this? Is there another way around this?

Additionally the dashboard table goes all the way to the bottom in the designs, there is no padding at the bottom of the page.

File: packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte (hunk 2 above)
Comment (MarkNerdi) [reply packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte]: the header containing the tabs and filter/search

File: packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte (hunk 1 above)
Comment (MarkNerdi) [reply packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte]: top navbar

File: packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte (hunk 2 above)
Comment (jeeanribeiro) [reply packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte]: `68px` is a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) and it could be avoided by putting it inside a named variable

File: packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte (hunk 1 above)
Comment (jeeanribeiro) [reply packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte]: `39px` is a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) and it could be avoided by putting it inside a named variable

**Review by jeeanribeiro — CHANGES_REQUESTED** [review]
[magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) needs to be avoided so we can understand the code

**Review by jeeanribeiro — CHANGES_REQUESTED** [review]
The last item in the scrollable activity list is being cut off even when the vertical scroll position is at the end of the scrollbar

image

**Review by jeeanribeiro — APPROVED** [review]

**Review by jeeanribeiro — APPROVED** [review]

**Review by jeeanribeiro — APPROVED** [review]
