### PR TITLE
fix: correctly validate bech32

### LINKED ISSUE #1071: 🐞 - Can add invalid Bech32 address to contact
### Task description

Steps to reproduce:

Add a new contact
Add a new invalid address in Bech32 format (e.g. by copying a valid address and changing one character)
Save

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/account/actions/isValidAddressFormatForNetwork.ts [hunk 1]
```diff
@@ -1,13 +1,15 @@
 import { NetworkId, isStardustNetwork } from '@core/network'
-import { isValidBech32AddressAndPrefix, validateEthereumAddress } from '@core/utils/crypto'
```
Comment (Tuditi) [inline packages/shared/src/lib/core/account/actions/isValidAddressFormatForNetwork.ts:2]: We need to get rid of this function and use `validateBech32Address` everywhere.

File: packages/shared/src/lib/core/account/actions/isValidAddressFormatForNetwork.ts [hunk 2]
```diff
@@ -1,13 +1,15 @@
...
     if (isStardustNetwork(destinationNetworkId)) {
-        return isValidBech32AddressAndPrefix(address, getNetworkHrp())
-            ? ''
-            : localize('error.address.invalidBech32Format')
+        try {
+            validateBech32Address(getNetworkHrp(), address)
+            return ''
+        } catch (error) {
+            return error as string
+        }
```
Comment (Tuditi) [inline packages/shared/src/lib/core/account/actions/isValidAddressFormatForNetwork.ts]: This function can use some improvement. It's used in `validateContactAddress` which throws an error. I would rename this function to `validateAddressFromatForNetwork` and propagate the error to `validateContactAddress` as is, because we throw an error based on the string we return here.

**Review by Tuditi — CHANGES_REQUESTED** [review]
Fixes the issue, but we have the same problem with deep links

**Review by Tuditi — APPROVED** [review]
LGTM!
