### PR TITLE
fix: use max gas fee when sending from L1 -> L2

### LINKED ISSUE #472: ️🛠 - Use max gas fee in amount of L2 transactions rather than estimatedGasFee
### Task description

We should add the max gas fee to the amount of an L2 transaction rather than the estimated gasFee, this is because the is the gas fee can be higher than the estimate but not the max, and we want the recipient user to always receive what the sender expected.

### Requirements

- add max gas fee to amount for L2 -> L2 transactions
- add max gas fee to amount for L1 -> L2 transactions

### PR DESCRIPTION
**Pull request by nicole-obrien**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by maxwellmattryan — DISMISSED** [review]
LGTM :cherry_blossom:

File: packages/desktop/views/dashboard/send-flow/views/components/StardustTransactionSummary.svelte [hunk 1]
```diff
@@ -71,21 +68,27 @@
...
     async function setGasVariables(sendFlowParameters: SendFlowParameters): Promise<void> {
-        estimatedGas = await estimateGasForLayer1ToLayer2Transaction(sendFlowParameters)
-        gasLimit = estimatedGas * GAS_LIMIT_MULTIPLIER
-        gasPrice = await getGasPriceInWei(sendFlowParameters.destinationNetworkId)
+        if (isToLayer2) {
+            const estimatedGas = await estimateGasForLayer1ToLayer2Transaction(sendFlowParameters)
+            const gasLimit = Math.floor(estimatedGas * GAS_LIMIT_MULTIPLIER)
+            const gasPrice = await getGasPriceInWei(sendFlowParameters.destinationNetworkId)
+            estimatedGasFee = calculateGasFeeInGlow(estimatedGas, gasPrice)
+            maxGasFee = calculateGasFeeInGlow(gasLimit, gasPrice)
```
Comment (maxwellmattryan) [inline packages/desktop/views/dashboard/send-flow/views/components/StardustTransactionSummary.svelte]: Would be beneficial to extract this logic into a separate function

File: packages/shared/src/lib/core/layer-2/constants/fallback-estimated-gas.constant.ts [hunk 2]
```diff
@@ -1,4 +1,4 @@
-import BigInteger from 'big-integer'
+import { SendFlowType } from '@core/wallet'
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/constants/fallback-estimated-gas.constant.ts:1]: Not in scope of this PR, but is this the best enum name for what this represents? If so we should be more specific with the existing variants (e.g. `NativeTokenUnwrapping`, `BaseCoinWrapping`, `BaseCoinTransfer`) and also use this type in places rather than random booleans that say if `isLayer2`. But we'd have to create a lot of variants for the possible combinations of transaction directions

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts [hunk 3]
```diff
@@ -9,42 +9,46 @@ import { getIscpTransferSmartContractData } from '../utils'
...
-                from: evmAddress,
-                to: ISC_MAGIC_CONTRACT_ADDRESS,
-                data,
-            })
-            return gas
-        } else {
-            return Promise.resolve(fallbackGas)
-        }
+        const gas = await getGasEstimateForMagicContractCall(destinationNetworkId, recipient?.address, transferredAsset)
+        return gas
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts:23]: Redundant variable initialization

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts [hunk 4]
```diff
@@ -9,42 +9,46 @@ import { getIscpTransferSmartContractData } from '../utils'
...
-
-    const chain = destinationNetworkId ? getNetwork()?.getChain(destinationNetworkId) : undefined
-    const provider = chain?.getProvider()
     const transferredAsset = getTransferredAsset(sendFlowParameters)
-
-    const fallbackGas = FALLBACK_ESTIMATED_GAS.toJSNumber()
-    if (!chain || !provider || !transferredAsset) {
-        return fallbackGas
-    }
+    if (!transferredAsset) return 0
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts]: Do we want brackets around if statements? I don't think the handbook mentions anything like this, and I'm personally a fan of one-line if statements but we should make some type of rule and add it to the handbook.

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts [hunk 5]
```diff
@@ -9,42 +9,46 @@ import { getIscpTransferSmartContractData } from '../utils'
...
     }
 }
 
+async function getGasEstimateForMagicContractCall(
+    networkId: NetworkId,
+    address: string | undefined,
+    transferredAsset: TransferredAsset
+): Promise<number> {
+    const chain = getNetwork()?.getChain(networkId)
+    if (!chain) return Promise.reject('Invalid chain')
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts]: See comment about if statements brackets

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts [hunk 6]
```diff
@@ -9,42 +9,46 @@ import { getIscpTransferSmartContractData } from '../utils'
...
+
+    const provider = chain?.getProvider()
+    if (!provider) return Promise.reject('Invalid provider')
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts]: See comment about if statements brackets

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts [hunk 7]
```diff
@@ -9,42 +9,46 @@ import { getIscpTransferSmartContractData } from '../utils'
...
+
+    if (!address) return Promise.reject('Invalid address')
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts]: See comment about if statements brackets

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts [hunk 8]
```diff
@@ -9,42 +9,46 @@ import { getIscpTransferSmartContractData } from '../utils'
...
+
+    const data = getIscpTransferSmartContractData(address, transferredAsset, chain)
+    if (!data) return Promise.reject('Invalid data')
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts]: See comment about if statements brackets

File: packages/shared/src/lib/core/wallet/utils/getOutputParameters.ts [hunk 9]
```diff
@@ -32,6 +35,14 @@ export async function getOutputParameters(
     const expirationUnixTime = expirationDate ? convertDateToUnixTimestamp(expirationDate) : undefined
     const timelockUnixTime = timelockDate ? convertDateToUnixTimestamp(timelockDate) : undefined
 
+    if (isToLayer2) {
+        const estimatedGas = await estimateGasForLayer1ToLayer2Transaction(sendFlowParameters)
+        const gasLimit = Math.floor(estimatedGas * GAS_LIMIT_MULTIPLIER)
+        const gasPrice = await getGasPriceInWei(destinationNetworkId)
+        const maxGasFee = calculateGasFeeInGlow(gasLimit, gasPrice)
+        amount = (parseInt(amount, 10) + Number(maxGasFee ?? 0)).toString()
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/wallet/utils/getOutputParameters.ts]: This logic is duplicated somewhat in the `StardustTransactionSummary` component, we should write a function

**Review by maxwellmattryan — DISMISSED** [review]
Have some changes requested :pray:

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts (hunk 3 above)
Comment (nicole-obrien) [reply packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts:23]: We want to handle the catching in this file so I need to await the response here rather than forwarding the promise to the caller

File: packages/desktop/views/dashboard/send-flow/views/components/StardustTransactionSummary.svelte (hunk 1 above)
Comment (nicole-obrien) [reply packages/desktop/views/dashboard/send-flow/views/components/StardustTransactionSummary.svelte]: done

File: packages/shared/src/lib/core/layer-2/constants/fallback-estimated-gas.constant.ts (hunk 2 above)
Comment (nicole-obrien) [reply packages/shared/src/lib/core/layer-2/constants/fallback-estimated-gas.constant.ts:1]: fair point

File: packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts (hunk 4 above)
Comment (nicole-obrien) [reply packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts]: brackets are in coding conventions I have updted them all

File: packages/shared/src/lib/core/wallet/utils/getOutputParameters.ts (hunk 9 above)
Comment (nicole-obrien) [reply packages/shared/src/lib/core/wallet/utils/getOutputParameters.ts]: done

**Review by Tuditi — DISMISSED** [review]
LGTM! :fire:

**Review by Tuditi — APPROVED** [review]
