### PR TITLE
fix: store tracked token as lowercase

### LINKED ISSUE #713: ️🛠 - Store evm addresses always in lowercase
### Task description

_No response_

### Requirements

- [ ] Store evm addresses always in lowercase

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/layer-2/actions/fetchSelectedAccountLayer2Balance.ts [hunk 1]
```diff
@@ -90,7 +90,7 @@ async function getLayer2Erc20BalancesForAddress(
                 continue
             }
             const rawBalance = await contract.methods.balanceOf(evmAddress).call()
-            erc20TokenBalances.push({ balance: rawBalance, tokenId: erc20Address })
+            erc20TokenBalances.push({ balance: Number(rawBalance), tokenId: erc20Address })
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/layer-2/actions/fetchSelectedAccountLayer2Balance.ts]: Perhaps we should use a `BigInt` for this? Let's make it a point to discuss on Monday what type of number format we should use.

**Review by maxwellmattryan — DISMISSED** [review]

**Review by Tuditi — APPROVED** [review]
LGTM :fire:
