### PR TITLE
refactor+fix: ledger app name check

### LINKED ISSUE #2764: ️🛠 - Fix ledger app check for iota testnet
### Task description

App is asking for shimmer app instead of iota app for iota testnet

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary

close #2764 

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [x] Windows

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by nicole-obrien** [comment]
This only considers onboarding, but we have a separate but similar piece of code once in the app and we need to connect a ledger app. That is also doing this wrong.

File: packages/shared/src/lib/core/profile/utils/getProfileLedgerAppName.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import { IOnboardingProfile, onboardingProfile } from '@contexts/onboarding'
+import { activeProfile } from '../stores'
+import { LedgerAppName } from '@core/ledger'
+import { get } from 'svelte/store'
+import { IProfile } from '../interfaces'
+import { SupportedStardustNetworkId } from '@core/network'
+
+export function getProfileLedgerAppName(
+    profile: IProfile | Partial<IOnboardingProfile> = get(onboardingProfile) ?? get(activeProfile)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/profile/utils/getProfileLedgerAppName.ts]: this needs to be in actions because its accesseing stores

**Review by nicole-obrien — COMMENTED** [review]
Looks good just one comment

**Review by nicole-obrien — APPROVED** [review]
