### PR TITLE
fix: address validation for network recipient inputs

### LINKED ISSUE #388: ️🛠 - Validate addresses on recipient selection in send flow
### Task description

Add validation to addresses on recipient selection in send flow

### Requirements

- [x] Add validation to the EVM address on recipient selection in send flow
- [x] Add validation to the smr address on recipient selection in send flow
- [ ] ~~Move validation logic to `NetworkRecipientSelector.svelte`~~

### PR DESCRIPTION
**Pull request by maxwellmattryan**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/utils/crypto/utils/validateEthereumAddress.ts [hunk 1]
```diff
@@ -1,27 +1,25 @@
...
+    } else if (!/^(0x)?[0-9a-f]{40}$/i.test(address)) {
+        throw new Error(localize('error.send.addressLength', { length: 42 }))
+        // 4. If not consistent capitalization then check EIP 55 checksum
+    } else if (!/^(0x)?[0-9a-f]{40}$/.test(address) || !/^(0x)?[0-9A-F]{40}$/.test(address)) {
         validateEthereumAddressChecksum(address)
     }
 }
 
-// Check if EIP-55 mixed-case checksum address encoding is followed (https://eips.ethereum.org/EIPS/eip-55)
+// Check if EIP-55 mixed-c0xe6bb6847ae56ea15941b106248ab7b463b3178abase checksum address encoding is followed (https://eips.ethereum.org/EIPS/eip-55)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/utils/crypto/utils/validateEthereumAddress.ts]: what is this?

**Review by nicole-obrien — APPROVED** [review]
