### PR TITLE
fix: fix L1->L2 flow

### LINKED ISSUE #199: ️🛠 - Fix L1 -> L2 flow
### Task description

With the release of the new testnet sending from L1 to L2 is broken. There are two reasons for this:

- `getEstimatedGasForTransferFromTransactionDetails` relies on asset, which doesn't have a chainId set in case of sending L1 token to L2, resulting in an undefined provider
- `getLayer2MetadataForTransfer` has changed with the new testnet

Firefly needs to update this as well, so reach out to Begona to fix this one together or see if they have fixed it when addressing this issue!

EVM Toolkit fix has been implemented here: https://github.com/iotaledger/evm-toolkit/pull/16

### Requirements

- [ ] Sending L1 <> L2 works.

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/dashboard/send-flow/views/SelectRecipientView.svelte [hunk 1]
```diff
@@ -104,6 +108,7 @@
             const asset = $newTransactionData.asset
             // L1 network
             const layer1Network = {
+                id: $network.getMetadata().id,
                 name: $network.getMetadata().name,
```
Comment (Tuditi) [inline packages/desktop/views/dashboard/send-flow/views/SelectRecipientView.svelte]: Maybe worth destructuring?

File: packages/shared/src/lib/core/layer-2/utils/getEstimatedGasForTransferFromTransactionData.ts [hunk 2]
```diff
@@ -14,12 +14,21 @@ export async function getEstimatedGasForTransferFromTransactionData(transactionD
...
-        )
+    const fallbackGas = GAS_BUDGET.toJSNumber()
+    if (asset && chainId) {
+        try {
+            const iscpTransferMethod = getIscpTransferMethod(address, asset, chainId, rawAmount)
+            if (iscpTransferMethod) {
+                const gas = await iscpTransferMethod.estimateGas()
+                return gas
+            }
+            return Promise.resolve(fallbackGas)
```
Comment (Tuditi) [inline packages/shared/src/lib/core/layer-2/utils/getEstimatedGasForTransferFromTransactionData.ts]: Use an explicit else here

File: packages/shared/src/lib/core/layer-2/utils/getEstimatedGasForTransferFromTransactionData.ts [hunk 3]
```diff
@@ -14,12 +14,21 @@ export async function getEstimatedGasForTransferFromTransactionData(transactionD
...
+        } catch (error) {
+            return Promise.resolve(fallbackGas)
```
Comment (Tuditi) [inline packages/shared/src/lib/core/layer-2/utils/getEstimatedGasForTransferFromTransactionData.ts]: Add a `console.error('Fallback gas used due to: ${error}`. Atm it's failing, and the console didn't show anything.

File: packages/shared/src/lib/core/layer-2/utils/getIrc30TransferSmartContractData.ts [hunk 4]
```diff
@@ -1,6 +1,11 @@
 import { IAsset } from '@core/wallet'
 import { getIscpTransferMethod } from './getIscpTransferMethod'
 
-export function getIrc30TransferSmartContractData(recipientAddress: string, asset: IAsset, amount: string): string {
-    return getIscpTransferMethod(recipientAddress, asset, amount)?.encodeABI() ?? ''
+export function getIrc30TransferSmartContractData(
+    recipientAddress: string,
+    asset: IAsset,
+    chainId: number,
+    amount: string
```
Comment (Tuditi) [inline packages/shared/src/lib/core/layer-2/utils/getIrc30TransferSmartContractData.ts]: I'm not a huge fan of passing this much arguments into a function. Also can we pass in chain instead of chainId?

**Review by Tuditi — CHANGES_REQUESTED** [review]
Some minor changes.

**Review by Tuditi — APPROVED** [review]
LGTM! :fire:
