### PR TITLE
fix: check valid preload path for Transak

### LINKED ISSUE #2045: ️🛠 - Check valid pre-load path for Transak manager
### Task description

Fix issue reported here: [transak.manager.ts : Check valid pre-load path](https://github.com/AuditOneAuditReviews/bloom_sc_audit_review/issues/6)

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary

closes #2045 

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [x] Windows

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/dashboard/buy-sell/components/TransakWindowPlaceholder.svelte [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+    function onButtonClick(): void {
+        openUrlInBrowser(DISCORD_URL)
+    }
+</script>
+
+<Pane
+    classes="flex flex-col justify-center items-center w-full h-full px-6 pb-6 pt-4 gap-4 bg-surface dark:bg-surface-dark shadow-lg"
+>
+    {#if error}
```
Comment (MarkNerdi) [inline packages/desktop/views/dashboard/buy-sell/components/TransakWindowPlaceholder.svelte:20]: should we also display something, if we dont have an api key for transak, or could that resulting error only occur in development?

**Review by MarkNerdi — APPROVED** [review]
