### PR TITLE
fix: don't override network with node info

### LINKED ISSUE #2474: ️🛠 - Don't override active profile network with node info during login
### Task description

_No response_

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by nicole-obrien**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/profile-manager/api/getNodeInfo.ts [hunk 1]
```diff
@@ -3,9 +3,7 @@ import { INodeInfoResponse } from '@core/network/interfaces/node-info-response.i
 import { getProfileManager } from '../stores'
 import { api } from '../api'
 
-export function getNodeInfo(url?: string, auth?: IAuth): Promise<INodeInfoResponse> | undefined {
+export async function getNodeInfo(url?: string, auth?: IAuth): Promise<INodeInfoResponse | undefined> {
```
Comment (Tuditi) [inline packages/shared/src/lib/core/profile-manager/api/getNodeInfo.ts:6]: Why is this async?

File: packages/shared/src/lib/core/network/actions/getNodeInfoWhileLoggedOut.ts [hunk 2]
```diff
@@ -18,16 +18,29 @@ export async function getNodeInfoWhileLoggedOut(url: string, auth: IAuth): Promi
             { stronghold: { snapshotPath: `${storagePath}/wallet.stronghold` } }
         )
         nodeInfoResponse = await api.getNodeInfo(manager?.id, url, auth)
+
+        await cleanupTemporaryProfile(manager, storagePath)
+
+        if (!nodeInfoResponse) {
+            return Promise.reject(new Error('error.node.invalidNode'))
+        }
```
Comment (Tuditi) [inline packages/shared/src/lib/core/network/actions/getNodeInfoWhileLoggedOut.ts]: This will still result in a runtime crash. The problem resides in passing an async function into the `continueButton` of `OnboardingLayout`. It is never awaited, which means that it results in a runtime crash when `getNodeInfoWhileLoggedOut` or `onContinueClick` throws/rejects.

**Review by Tuditi — CHANGES_REQUESTED** [review]
I think I found the issue we talked about before. Let me know if this is not the case.

File: packages/shared/src/lib/core/profile-manager/api/getNodeInfo.ts (hunk 1 above)
Comment (MarkNerdi) [reply packages/shared/src/lib/core/profile-manager/api/getNodeInfo.ts:6]: not required, but IMO you can see faster that you have to await this if this keyword is present

File: packages/shared/src/lib/core/network/actions/getNodeInfoWhileLoggedOut.ts (hunk 2 above)
Comment (MarkNerdi) [reply packages/shared/src/lib/core/network/actions/getNodeInfoWhileLoggedOut.ts]: we catch this errror in `CustomNetworkView` as we have a trycatch around the whole validation and fetching

**Review by Tuditi — APPROVED** [review]

**Review by MarkNerdi — APPROVED** [review]
