### PR TITLE
fix: error converting large number to big int

### LINKED ISSUE #1616: 🐞 - Invalid BigNumber String when transfering 5000 DEEPR (smaller amounts work)
### Version

0.1.2

### Description

Sending anything over 5000 DEEPR causes the error in the picture. Other tokens I can slap the "use Max" button and fire away. Using very small amounts of DEEPR works, up to at least 500 

### Expected behaviour

send DEEPR

### Actual behaviour

Invalid BigNumber error message
deepr

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

_No response_

### Crash Status

None of the above

### Error Messages

deepr

### Error Logs

_No response_

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1624: ️🛠 - Fix issue with large number of decimal places in send flow
### Task description

- Users have reported issues when sending ERC-20 tokens, because they have upto 18 decimal places, there seems to be an issue with big int somewhere 

Image

### Requirements

- Fix issue with big ints in send flow

### PR DESCRIPTION
**Pull request by nicole-obrien**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

closes: https://github.com/bloomwalletio/bloom/issues/1616

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jeeanribeiro — DISMISSED** [review]
The number loses its precision if its too big, leading to wrong numbers

Maximum supported would be:
`BigInt(Number("10000000000000000000000"))`

Precision will be lost starting by this one:
`BigInt(Number("10000000000000000000001"))`

I think it is better to address big numbers handling rather than merging how it is now, otherwise users that should be affected by the converting error will be transferring wrong amounts.

**Comment by nicole-obrien** [comment]
> The number loses its precision if its too big, leading to wrong numbers
> 
> Maximum supported would be: `BigInt(Number("10000000000000000000000"))`
> 
> Precision will be lost starting by this one: `BigInt(Number("10000000000000000000001"))`
> 
> I think it is better to address big numbers handling rather than merging how it is now, otherwise users that should be affected by the converting error will be transferring wrong amounts.

Okay I started working on the bigger refactor to use bigint type everywhere in send flow etc for rawamount.

Some problems still to fix after my latest pushes if you could take a look:
- Token Amount with Slider is needs refactoring to use bigint
- Can currently enter more than the max available balance in the send form token input

Then we need to review and test as much as possible L1 -> L1, L1 -> L2, L2 -> L2 (IRC30, ERC20), L2 -> L1

**Review by MarkNerdi — DISMISSED** [review]

File: packages/shared/src/lib/core/token/utils/convertToRawAmount.ts [hunk 1]
```diff
@@ -18,29 +16,37 @@ function convertToRawAmountFromMetadata(
...
-): Big | undefined {
+): bigint | undefined {
+    const [min, max] = bigIntMinAndMax(tokenMetadata.decimals, MAX_SUPPORTED_DECIMALS)
+
     if (tokenMetadata?.standard === TokenStandard.BaseToken) {
-        if (tokenMetadata.useMetricPrefix) {
-            const decimals = IOTA_UNIT_MAP?.[selectedUnit?.substring(0, 1) as IotaUnit]?.decimalPlaces ?? 0
-            return convertAmountToMatchUnit(amount, decimals)
+        if (!selectedUnit || selectedUnit === tokenMetadata.unit) {
+            return convertFloatToBigInt(amount, max)
```
Comment (MarkNerdi) [inline packages/shared/src/lib/core/token/utils/convertToRawAmount.ts]: i needed to change this to `min` so that it works correctly, else it converted 1SMR into 1 * 10^24 GLOW. Any reason for this?

File: packages/shared/src/components/inputs/TokenAmountInput.svelte
Comment (Tuditi) [inline packages/shared/src/components/inputs/TokenAmountInput.svelte:1]: Update the validate function in the same fashion as `TokenAmountWithSliderInput` to get rid of the returned promise.

File: packages/desktop/views/dashboard/send-flow/views/InputTokenAmountView.svelte
Comment (Tuditi) [inline packages/desktop/views/dashboard/send-flow/views/InputTokenAmountView.svelte:1]: The `rawAmount` property has to become a string in this component.

File: packages/shared/src/lib/core/layer-2/classes/special-stream.class.ts [hunk 2]
```diff
@@ -1,10 +1,9 @@
-import { WriteStream, ReadStream } from '@iota/util.js'
-import BigInteger from 'big-integer'
```
Comment (Tuditi) [inline packages/shared/src/lib/core/layer-2/classes/special-stream.class.ts:2]: We can remove this from package.json as well.

File: packages/shared/src/lib/core/token/utils/validateTokenAmount.ts
Comment (Tuditi) [inline packages/shared/src/lib/core/token/utils/validateTokenAmount.ts:1]: Remove commented out code in this file.

File: packages/shared/src/lib/core/wallet/types/send-flow-parameter.type.ts [hunk 3]
```diff
@@ -35,7 +35,7 @@ export interface NftSendFlowParameters extends Omit<BaseSendFlowParameters, 'typ
 
 // TODO move to own file and check optional params
```
Comment (Tuditi) [inline packages/shared/src/lib/core/wallet/types/send-flow-parameter.type.ts]: It's a good time to address this comment.

**Review by Tuditi — CHANGES_REQUESTED** [review]
The following scenario is not working:

1) Mint 21 000 000 Ethereum with 18 decimal places.
2) Try to send max available balance.

IIUC, the reason for this is the  `ITokenBalance` interface, which is still a number instead of a BigInt.

I haven't tested ERC-20 transfers due to another bug. Will test when the requested changes are addressed.

**Comment by nicole-obrien** [comment]
We should not need formatTokenAmountPrecise and formatTokenAmountDefault, now we have replaced formatTokenAmountBestMatch to work with bigint, and it has a flag for rounding or not.

**Review by MarkNerdi — COMMENTED** [review]
Works for me :+1:

**Review by Tuditi — DISMISSED** [review]

File: packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte [hunk 4]
```diff
@@ -7,13 +7,14 @@
...
+    export let rawAmount: bigint = BigInt(0)
 
     let tokenAmountInput: TokenAmountWithSliderInput
+    let amount: string
 
-    async function onContinueClick(): Promise<void> {
+    function onContinueClick(): void {
         try {
-            await tokenAmountInput.validate()
+            tokenAmountInput.validate()
```
Comment (nicole-obrien) [inline packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte]: why is this no longer awaited?

File: packages/desktop/components/popup/popups/ManageVotingPowerPopup.svelte [hunk 5]
```diff
@@ -46,7 +46,7 @@
 
     async function onSubmit(): Promise<void> {
         try {
-            await tokenAmountInput?.validate(true)
+            tokenAmountInput?.validate(true)
```
Comment (nicole-obrien) [inline packages/desktop/components/popup/popups/ManageVotingPowerPopup.svelte]: why is this no longer awaited?

File: packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionSummary.svelte [hunk 6]
```diff
@@ -26,20 +26,20 @@
...
     }
 
-    $: storageDeposit = getTransactionStorageDeposit(sendFlowParameters) ?? 0
-    function getTransactionStorageDeposit(_sendFlowParameters: SendFlowParameters) {
+    $: storageDeposit = getTransactionStorageDeposit(sendFlowParameters) ?? BigInt(0)
+    function getTransactionStorageDeposit(_sendFlowParameters: SendFlowParameters): bigint {
         if (_sendFlowParameters.type === SendFlowType.TokenTransfer) {
             if (_sendFlowParameters.destinationNetworkId !== _sendFlowParameters.tokenTransfer.token.networkId) {
-                return L2_TO_L1_STORAGE_DEPOSIT_BUFFER[SendFlowType.TokenUnwrap] ?? 0
+                return BigInt(L2_TO_L1_STORAGE_DEPOSIT_BUFFER[SendFlowType.TokenUnwrap] ?? 0)
```
Comment (nicole-obrien) [inline packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionSummary.svelte:33]: Should we store these constants as big ints?

File: packages/desktop/views/dashboard/wallet/tab-section/portfolio/components/TokenListRow.svelte [hunk 7]
```diff
@@ -16,22 +16,20 @@
             return '-'
         }
 
-        let tokenSupply: number | undefined
+        let tokenSupply: TokenSupply | '0'
```
Comment (nicole-obrien) [inline packages/desktop/views/dashboard/wallet/tab-section/portfolio/components/TokenListRow.svelte:19]: Should TokenSupply be a bigint?

File: packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte [hunk 8]
```diff
@@ -117,17 +117,17 @@
     }
 
     async function getAccountBalanceFromAccount(account: IAccount): Promise<IAccountBalance> {
-        const alias = (await account.getMetadata())?.alias
+        const alias = account.getMetadata()?.alias
```
Comment (nicole-obrien) [inline packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte:120]: Every other account method returns a promise, when did this one change?

File: packages/shared/src/components/inputs/Input.svelte [hunk 9]
```diff
@@ -103,11 +103,8 @@
             if (pasteVal?.indexOf('e') >= 0 || pasteVal?.indexOf('-') >= 0) {
                 event.preventDefault()
             } else if (float) {
-                const val = parseCurrency(pasteVal)
-                // Discard any numbers we can't parse as floats
-                if (Number.isNaN(val)) {
```
Comment (nicole-obrien) [inline packages/shared/src/components/inputs/Input.svelte:108]: Do we no longer need to check that this is float when we paste a value in?

File: packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte [hunk 10]
```diff
@@ -31,50 +28,53 @@
...
+            ((token.metadata.standard === TokenStandard.BaseToken && unit === token.metadata.subunit) ||
+                (unit === getUnitFromTokenMetadata(token.metadata) && token.metadata.decimals === 0)) &&
+            Number.parseInt(inputtedAmount, 10).toString() !== inputtedAmount
         ) {
             error = localize('error.send.amountNoFloat')
-        } else if (bigAmount.gt(Big(availableBalance))) {
+        } else if (rawAmount && rawAmount > availableBalance) {
             error = localize('error.send.amountTooHigh')
-        } else if (bigAmount.lte(Big(0))) {
+        } else if (rawAmount && rawAmount <= 0) {
```
Comment (nicole-obrien) [inline packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte:61]: does this 0 need to be bigint?

File: packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts [hunk 11]
```diff
@@ -3,7 +3,7 @@ import { AmountNotAnIntegerError, SendTransactionParameter } from '@auxiliary/de
 export function getRawAmountFromSearchParam(
     searchParams: URLSearchParams,
     parameterKey: SendTransactionParameter
-): string {
+): bigint {
     let rawAmount = searchParams.get(parameterKey)
     const amount = Number(rawAmount)
     if (!Number.isInteger(amount)) {
```
Comment (nicole-obrien) [inline packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts]: number might be greater than max safe int? Better to do a regular expression here for an int?

File: packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts [hunk 12]
```diff
@@ -12,5 +12,5 @@ export function getRawAmountFromSearchParam(
     if (amount < 0) {
         rawAmount = Math.abs(amount).toString()
     }
-    return rawAmount
+    return BigInt(rawAmount)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts]: type issues, raw amoount can be null?

**Review by nicole-obrien — COMMENTED** [review]
Review part 1

**Comment by jeeanribeiro** [comment]
I tried to mint a native token with the following supply `1_000_000_000_000_000_000_000_000_000_000` but precision was lost

image

**Comment by jeeanribeiro** [comment]
SliderInput does not support large numbers

image

**Comment by jeeanribeiro** [comment]
It is not possible to burn large number native tokens, it shows this error

image

File: packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte (hunk 4 above)
Comment (Tuditi) [reply packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte]: Because `tokenAmountInput` is a `TokenAmountWithSliderInput`, of which the `validate` call isn't async anymore.

File: packages/desktop/components/popup/popups/ManageVotingPowerPopup.svelte (hunk 5 above)
Comment (Tuditi) [reply packages/desktop/components/popup/popups/ManageVotingPowerPopup.svelte]: Same reason as above.

File: packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte (hunk 4 above)
Comment (nicole-obrien) [reply packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte]: ahh I think i just looked at token amount input component and seen that it was async, perhaps renaming the variable to match the component would help the confusion

Comment (Tuditi) [reply packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte]: Done

File: packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte (hunk 8 above)
Comment (Tuditi) [reply packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte:120]: It was touched 9 months ago. I think it's just a remnant of the previous bindings.

https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/lib/wallet/account.ts#L877

File: packages/desktop/views/dashboard/wallet/tab-section/portfolio/components/TokenListRow.svelte (hunk 7 above)
Comment (Tuditi) [reply packages/desktop/views/dashboard/wallet/tab-section/portfolio/components/TokenListRow.svelte:19]: TS doesn't allow bigints for computed enum member values. As long as it's a string instead of a number, it's okay.

Ref: https://github.com/microsoft/TypeScript/issues/40793

File: packages/shared/src/components/inputs/Input.svelte (hunk 9 above)
Comment (Tuditi) [reply packages/shared/src/components/inputs/Input.svelte:108]: This check is already happening is `parseCurrency`. Although, you're comment did unravel a mistake in the parseCurrency function.

Instead of calling `preventDefault`, parseCurrency returns '0' in case the value cannot be parsed as a float.

File: packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte (hunk 10 above)
Comment (Tuditi) [reply packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte:61]: You can make comparisons between Numbers and BigInt's.

image

File: packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts (hunk 11 above)
Comment (Tuditi) [reply packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts]: Yup, that makes sense

File: packages/desktop/components/popup/popups/MintNativeTokenFormPopup.svelte [hunk 13]
```diff
@@ -205,7 +205,7 @@
         <optional-inputs class="flex flex-row flex-wrap gap-4">
             <OptionalInput
                 bind:value={decimals}
-                inputType="number"
+                inputType="BigInt"
```
Comment (nicole-obrien) [inline packages/desktop/components/popup/popups/MintNativeTokenFormPopup.svelte]: why does this need to be a BigInt? And isn't the type `bigint`, then it gives a type error above? We only check if something is number or string in the closable input component.

File: packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionSummary.svelte (hunk 6 above)
Comment (nicole-obrien) [reply packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionSummary.svelte:33]: This enum / constant is now bigint, so you only need to cast the 0?

File: packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts [hunk 14]
```diff
@@ -3,14 +3,14 @@ import { AmountNotAnIntegerError, SendTransactionParameter } from '@auxiliary/de
 export function getRawAmountFromSearchParam(
     searchParams: URLSearchParams,
     parameterKey: SendTransactionParameter
-): string {
-    let rawAmount = searchParams.get(parameterKey)
-    const amount = Number(rawAmount)
-    if (!Number.isInteger(amount)) {
+): bigint {
+    const rawAmount = searchParams.get(parameterKey) ?? '0'
+    if (!new RegExp('^[+|-]{1}?\\d+$').test(rawAmount)) {
```
Comment (nicole-obrien) [inline packages/shared/src/lib/auxiliary/deep-link/utils/getRawAmountFromSearchParam.ts]: This regular expression doewsn't work, it seems to want at least 1 `+` or `-` and the \\d should be `\d`

If this is used in more than one place we should store this as a constant and or a util function

File: packages/shared/src/lib/core/activity/utils/evm/generateSmartContractActivity.ts [hunk 15]
```diff
@@ -14,7 +14,7 @@ export async function generateSmartContractActivity(
 
     const baseTokenTransfer = {
         tokenId: BASE_TOKEN_ID,
-        rawAmount: String(transaction.value ?? '0'),
+        rawAmount: BigInt(String(transaction.value ?? '0')),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/evm/generateSmartContractActivity.ts]: is this the correct way to convert bigintlike to bigint? if so we should have a util function

File: packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts [hunk 16]
```diff
@@ -13,8 +13,19 @@ export async function generateTokenBalanceChangeActivity(
     balanceChange: ITokenBalanceChange,
     account: IAccountState
 ): Promise<TransactionActivity> {
-    const difference = balanceChange.newBalance - (balanceChange.oldBalance ?? 0)
+    // Cast as a BigInt due to legacy data structures
+    const newBalance = BigInt(
+        isScientificNotation(balanceChange.newBalance) ? Number(balanceChange.newBalance) : balanceChange.newBalance
+    )
+    const oldBalance = BigInt(
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts]: this casting should be a util function

File: packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts [hunk 17]
```diff
@@ -13,8 +13,19 @@ export async function generateTokenBalanceChangeActivity(
...
+        isScientificNotation(balanceChange.oldBalance ?? 0)
+            ? Number(balanceChange.oldBalance)
+            : balanceChange.oldBalance ?? 0
+    )
+
+    const difference = newBalance - oldBalance
     const direction = difference >= 0 ? ActivityDirection.Incoming : ActivityDirection.Outgoing
+    const rawAmount = direction === ActivityDirection.Incoming ? difference : difference * BigInt(-1)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts]: We never previously used a signed value for rawAmount, but relied on the direction when displaying a minus etc to the user. Why are we multiplying by -1?

**Review by nicole-obrien — COMMENTED** [review]
Review pt2

File: packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts [hunk 18]
```diff
@@ -32,7 +32,7 @@ export function getGovernanceInfo(output: Output, inputs: IWrappedOutput[], meta
                         ? GovernanceAction.IncreaseVotingPower
                         : GovernanceAction.DecreaseVotingPower,
                 votingPower: currentVotingPower,
-                votingPowerDifference: Math.abs(currentVotingPower - oldVotingPower),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts:35]: why are we removing absolute?

File: packages/shared/src/lib/core/wallet/utils/buildFoundryOutputBuilderParams.ts [hunk 19]
```diff
@@ -13,19 +13,16 @@ import { getSerialNumberFromAliasOutput } from '@core/activity/utils/outputs/get
 import { IIrc30Metadata } from '@core/token/interfaces'
 
 export async function buildFoundryOutputBuilderParams(
-    totalSupply: number,
-    circulatingSupply: number,
+    totalSupply: string,
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/wallet/utils/buildFoundryOutputBuilderParams.ts]: not the end of the world, but we cast these values to bigint validate them on the mint form, then store them as string and then cast them again here? Shouldn't we just store them as bigint

File: packages/shared/src/lib/core/wallet/interfaces/mint-token-details.interface.ts [hunk 20]
```diff
@@ -1,7 +1,7 @@
 export interface IMintTokenDetails {
     name: string
-    totalSupply: number
-    circulatingSupply: number
+    totalSupply: string
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/wallet/interfaces/mint-token-details.interface.ts]: could these be bigint?

File: packages/shared/src/lib/core/wallet/actions/updateL2BalanceWithoutActivity.ts [hunk 21]
```diff
@@ -4,11 +4,11 @@ import { updateLayer2AccountBalanceForTokenOnChain } from '@core/layer-2/stores'
...
 export async function updateL2BalanceWithoutActivity(
-    rawAmount: number,
+    rawAmount: bigint,
     tokenId: string,
     account: IAccountState,
     networkId: NetworkId
 ): Promise<void> {
     const newBalance = updateLayer2AccountBalanceForTokenOnChain(account.index, networkId, tokenId, rawAmount)
-    await calculateAndAddPersistedTokenBalanceChange(account, networkId, tokenId, newBalance, true)
+    await calculateAndAddPersistedTokenBalanceChange(account, networkId, tokenId, newBalance.toString(), true)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/wallet/actions/updateL2BalanceWithoutActivity.ts]: we convert this to string but later convert it to a bigint with aditional checks? is there a reason it needs to be string here

File: packages/shared/src/lib/core/wallet/actions/mintNativeToken.ts [hunk 22]
```diff
@@ -13,16 +13,15 @@ import { getTransactionOptions, sendPreparedTransaction } from '../utils'
 import { getActiveNetworkId } from '@core/network'
 
 export async function mintNativeToken(
-    maximumSupply: number,
-    circulatingSupply: number,
+    maximumSupply: string,
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/wallet/actions/mintNativeToken.ts]: another place mint should just be bigint

File: packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts [hunk 23]
```diff
@@ -30,7 +30,7 @@ export function createEvmChainToEvmChainTransaction(
     ) {
         const tokenAmount = getAmountAndTokenFromSendFlowParameters(sendFlowParameters)
         const token = tokenAmount.token
-        const amount = tokenAmount.amount
+        const amount = tokenAmount.amount?.toString()
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts]: if this is required to be a string somewwhere deeper, we should cast it there. i.e. if this needs to be a string as the output of buildEvmTransactionDataForToken then we should do the type tansformation in there.

Comment (nicole-obrien) [reply packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts]: just looked and its mostly used / casted as a bigint deeper anyway

**Review by nicole-obrien — COMMENTED** [review]
Review pt3

File: packages/shared/src/lib/core/utils/convert.ts [hunk 24]
```diff
@@ -233,6 +233,7 @@ export class Converter {
     }
 
     public static bigIntToHex(bigInt: bigint, prefix = true): string {
+        bigInt = BigInt(bigInt)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/utils/convert.ts:238]: why is that needed?

File: packages/desktop/components/popup/popups/MintNativeTokenFormPopup.svelte (hunk 13 above)
Comment (Tuditi) [reply packages/desktop/components/popup/popups/MintNativeTokenFormPopup.svelte]: This was an accidental rename, I will revert.

File: packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts (hunk 17 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts]: Because we used to call `Math.abs()` on the number on line.33 before. Since it is a  BigInt, this option is not available.

File: packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts (hunk 18 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts:35]: We don't have `Math.abs()` for BigInt's.

File: packages/shared/src/lib/core/wallet/utils/buildFoundryOutputBuilderParams.ts (hunk 19 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/wallet/utils/buildFoundryOutputBuilderParams.ts]: The issue is that we get these values from `NumberInput` as a string and then set them reactively. I could cast them as a BigInt by introducing an extra variable if you want.

File: packages/shared/src/lib/core/wallet/interfaces/mint-token-details.interface.ts (hunk 20 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/wallet/interfaces/mint-token-details.interface.ts]: Relates to the comment above.

File: packages/shared/src/lib/core/wallet/actions/updateL2BalanceWithoutActivity.ts (hunk 21 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/wallet/actions/updateL2BalanceWithoutActivity.ts]: This is because atm token balance changes are persisted as a string. Alternatively, we can write a migration function that converts them all to BigInt's.

File: packages/shared/src/lib/core/wallet/actions/mintNativeToken.ts (hunk 22 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/wallet/actions/mintNativeToken.ts]: Relates to mint token details interface.

File: packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts (hunk 17 above)
Comment (nicole-obrien) [reply packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts]: But if we originally where ensuring this was always a positive integer what are we doing now?
We could have a util to strip the sign from the front of the bigint

File: packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts (hunk 18 above)
Comment (nicole-obrien) [reply packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts:35]: But if we originally where ensuring this was always a positive integer what are we doing now?
We could have a util to strip the sign from the front of the bigint

File: packages/shared/src/lib/core/wallet/actions/updateL2BalanceWithoutActivity.ts (hunk 21 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/wallet/actions/updateL2BalanceWithoutActivity.ts]: I just tried this, but it doesn't work. Below is an excerpt from the code of persistent stores. You can't store anything that cannot be `JSON.stringify()`-d. 
image

File: packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts (hunk 23 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts]: The reason for this was that the calculate gas expects it as a string, but I convert the bigint there.

File: packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts [hunk 25]
```diff
@@ -13,7 +13,10 @@ export async function generateTokenBalanceChangeActivity(
     balanceChange: ITokenBalanceChange,
     account: IAccountState
 ): Promise<TransactionActivity> {
-    const difference = balanceChange.newBalance - (balanceChange.oldBalance ?? 0)
+    const newBalance = legacyNumberToBigInt(balanceChange.newBalance)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/evm/generateTokenBalanceChangeActivity.ts]: We have Converter.xxx for other converter functions should this be moved there?

File: packages/shared/src/lib/core/activity/utils/generateActivitiesFromBasicOutputs.ts [hunk 26]
```diff
@@ -136,35 +136,37 @@ function didTokensGetBurned(
...
+function getAllNativeTokensFromOutputs(outputs: IWrappedOutput[]): { [key: string]: bigint } {
+    const nativeTokens: { [key: string]: bigint } = {}
     for (const output of outputs) {
         for (const nativeToken of output.output?.nativeTokens ?? []) {
             if (!nativeTokens[nativeToken.id]) {
-                nativeTokens[nativeToken.id] = 0
+                nativeTokens[nativeToken.id] = BigInt(0)
             }
-            nativeTokens[nativeToken.id] += Number(nativeToken.amount)
+            nativeTokens[nativeToken.id] += BigInt(nativeToken.amount)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/generateActivitiesFromBasicOutputs.ts:169]: native token is already bigint, so no need to cast?

File: packages/shared/src/lib/core/activity/utils/generateBaseActivity.ts [hunk 27]
```diff
@@ -70,7 +70,7 @@ export async function generateBaseActivity(
         persistedToken && nativeToken
             ? {
                   tokenId: persistedToken.id,
-                  rawAmount: String(Number(nativeToken.amount)),
+                  rawAmount: BigInt(nativeToken.amount),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/generateBaseActivity.ts:73]: native token type says it is already a bigint

File: packages/shared/src/lib/core/activity/utils/generateSingleBasicActivity.ts [hunk 28]
```diff
@@ -12,20 +12,18 @@ export async function generateSingleBasicActivity(
...
-    overrideAmount?: number
+    overrideAmount?: bigint
 ): Promise<TransactionActivity> {
     const baseActivity = await generateBaseActivity(account, networkId, generationParameters)
 
     if (baseActivity.smartContract) {
-        const transferAmount = baseActivity.smartContract.baseTokens
-            ? Number(baseActivity.smartContract.baseTokens ?? '0')
-            : 0
+        const transferAmount = BigInt(baseActivity.smartContract.baseTokens ? baseActivity.smartContract.baseTokens : 0)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/generateSingleBasicActivity.ts]: bigintlike to bigint convertor function to be used here?

File: packages/shared/src/lib/core/activity/utils/generateSingleFoundryActivity.ts [hunk 29]
```diff
@@ -47,9 +47,9 @@ export async function generateSingleFoundryActivity(
         recipient: { type: SubjectType.Account, account, address: account.depositAddress },
         type: ActivityType.Foundry,
         aliasAddress,
-        mintedTokens: mintedTokens.toString(),
-        meltedTokens: meltedTokens.toString(),
-        maximumSupply: maximumSupply.toString(),
+        mintedTokens: BigInt(mintedTokens).toString(),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/generateSingleFoundryActivity.ts]: already a bigint, and why dont we dont use bigint to store these values in the activity

File: packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts [hunk 30]
```diff
@@ -47,7 +47,7 @@ export function getTransactionAssets(
             tokenTransfer:
                 token && tokenAmount
                     ? {
-                          rawAmount: tokenAmount,
+                          rawAmount: BigInt(tokenAmount),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts]: this is already bigint

File: packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts [hunk 31]
```diff
@@ -27,7 +27,7 @@ export function getTransactionAssets(
         activity.action === ActivityAction.Burn
             ? undefined
             : {
-                  rawAmount: activity.baseTokenTransfer.rawAmount,
+                  rawAmount: BigInt(activity.baseTokenTransfer.rawAmount),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts]: this is already bigint

File: packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts [hunk 32]
```diff
@@ -60,7 +60,7 @@ export function getTransactionAssets(
         const amount = isVotingPowerActivity ? activity.votingPowerDifference : activity.votingPower
         return {
             baseCoinTransfer: {
-                rawAmount: String(amount),
+                rawAmount: BigInt(amount ?? 0),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts]: bigintlike to bigint convertor?

File: packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts [hunk 33]
```diff
@@ -84,11 +84,11 @@ async function getLayer2NativeTokenBalancesForAddress(
         const contract = chain.getContract(ContractType.IscMagic, ISC_MAGIC_CONTRACT_ADDRESS)
         const nativeTokenResult = (await contract.methods
             .callView(accountsCoreContract, getBalanceFunc, parameters)
-            .call()) as { items: KeyValue<number>[] }
+            .call()) as { items: KeyValue<string>[] }
 
         const nativeTokens = nativeTokenResult.items.map((item) => ({
             tokenId: item.key,
-            balance: Math.floor(Number(item.value)),
+            balance: BigInt(item.value),
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts]: is the new convertor function safer here for type any?

File: packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts [hunk 34]
```diff
@@ -116,7 +113,7 @@ async function getLayer2Erc20BalancesForAddress(
                 continue
             }
             const rawBalance = await contract.methods.balanceOf(evmAddress).call()
-            erc20TokenBalances.push({ balance: Math.floor(Number(rawBalance)), tokenId: erc20Address })
+            erc20TokenBalances.push({ balance: BigInt(rawBalance), tokenId: erc20Address })
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts]: is the new convertor function safer here for type any?

File: packages/shared/src/lib/core/layer-2/actions/getGasFeeForLayer1ToLayer2Transaction.ts [hunk 35]
```diff
@@ -6,31 +6,31 @@ import { AssetType } from '../enums'
...
+        return BigInt(0)
     }
 
     try {
         const gasEstimate = await getGasEstimateForIscpCall(destinationNetworkId, sendFlowParameters)
         return gasEstimate
     } catch (err) {
         console.error(err)
-        return FALLBACK_ESTIMATED_GAS[sendFlowParameters.type]
+        return BigInt(FALLBACK_ESTIMATED_GAS[sendFlowParameters.type])
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/layer-2/actions/getGasFeeForLayer1ToLayer2Transaction.ts:26]: estimated gas cost can be stored as bigint

File: packages/shared/src/lib/core/layer-2/helpers/calculateGasFeeInGlow.ts [hunk 36]
```diff
@@ -1,10 +1,10 @@
 import { BigIntLike } from '@ethereumjs/util'
 import { WEI_PER_GLOW } from '../constants/wei.constants'
 
-export function calculateGasFeeInGlow(gasAmount: BigIntLike, gasPriceInWei: BigIntLike | undefined): BigIntLike {
+export function calculateGasFeeInGlow(gasAmount: BigIntLike, gasPriceInWei: BigIntLike | undefined): bigint {
     if (gasAmount && gasPriceInWei) {
         const gasPriceInGlow = BigInt(Number(gasPriceInWei)) / WEI_PER_GLOW
-        return BigInt(Number(gasAmount) * Number(gasPriceInGlow)).toString()
+        return BigInt(Number(gasAmount) * Number(gasPriceInGlow))
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/layer-2/helpers/calculateGasFeeInGlow.ts]: would be better to convert gasAmount to bigint using converter before calculation instead of working in numbers and losing precision?

File: packages/shared/src/lib/core/layer-2/helpers/getEvmTransactionValueFromAmount.ts [hunk 37]
```diff
@@ -1,6 +1,6 @@
 import { HEX_PREFIX } from '@core/utils'
 import { WEI_PER_GLOW } from '../constants'
 
-export function getEvmTransactionValueFromAmount(amount: number | string): string {
-    return HEX_PREFIX + BigInt(BigInt(amount) * WEI_PER_GLOW).toString(16)
+export function getEvmTransactionValueFromAmount(amount: bigint): string {
+    return HEX_PREFIX + BigInt(amount * WEI_PER_GLOW).toString(16)
```
Comment (nicole-obrien) [inline packages/shared/src/lib/core/layer-2/helpers/getEvmTransactionValueFromAmount.ts]: why cast to bigint if you are already multiplying two bigints?

**Review by nicole-obrien — COMMENTED** [review]
Review pt4

File: packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts (hunk 18 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/helper/getGovernanceInfo.ts:35]: I created a `BigIntAbs()` function

File: packages/shared/src/lib/core/utils/convert.ts (hunk 24 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/utils/convert.ts:238]: To ensure that `bigInt` is of type `bigint`

File: packages/shared/src/lib/core/activity/utils/generateActivitiesFromBasicOutputs.ts (hunk 26 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/generateActivitiesFromBasicOutputs.ts:169]: At the moment they are hex encoded strings. I will create reproduction steps for the SDK team to fix this.

Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/generateActivitiesFromBasicOutputs.ts:169]: It's typed wrongly on the SDK, it's actually a hex encoded string. See https://github.com/iotaledger/iota-sdk/issues/1839

File: packages/shared/src/lib/core/activity/utils/generateBaseActivity.ts (hunk 27 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/generateBaseActivity.ts:73]: Same comment as above.

File: packages/shared/src/lib/core/activity/utils/generateSingleBasicActivity.ts (hunk 28 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/generateSingleBasicActivity.ts]: I improved it using the nullish coalescing operator. No need to import extra convertor class here.

File: packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts (hunk 32 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts]: Amount is already bigint, so I just nullish coalesced it into BigInt(0).

File: packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts (hunk 33 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts]: BigInt is able to convert hex encoded strings, the new convertor function is useful, because it takes care in case of BigIntLike types that can be of type buffer. The response should not be returned by the smart contract in buffer format.

File: packages/shared/src/lib/core/layer-2/actions/getGasFeeForLayer1ToLayer2Transaction.ts (hunk 35 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/layer-2/actions/getGasFeeForLayer1ToLayer2Transaction.ts:26]: It's less duplication if we convert it here. We also need it as a number in `canAccountMakeEvmTransaction`.

File: packages/shared/src/lib/core/layer-2/helpers/calculateGasFeeInGlow.ts (hunk 36 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/layer-2/helpers/calculateGasFeeInGlow.ts]: No, because we are multiplying with a factor of 1.1 in `canAccountMakeEvmTransaction`, which is not possible with big ints.

File: packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts (hunk 34 above)
Comment (Tuditi) [reply packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts]: Same response as above.

**Review by nicole-obrien — COMMENTED** [review]
Good to approve 🙏

**Review by Tuditi — APPROVED** [review]
Works for me, so let's bit the :bullettrain_front:
