### PR TITLE
fix: fetch metadata from foundry if not ERC20

### LINKED ISSUE #1225: ️🛠 - Fix native token metadata fetching
### Task description

When a user is receiving wrapped native tokens based from a foundry they don't own, the metadata is not correctly fetched.

### Requirements

_TBD_

### PR DESCRIPTION
**Pull request by maxwellmattryan**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [x] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/token/actions/requestPersistedToken.ts [hunk 1]
```diff
@@ -22,11 +24,24 @@ export async function requestPersistedToken(
...
-            /* eslint-disable @typescript-eslint/no-unnecessary-type-assertion */
-            tokenMetadata = await getErc20TokenMetadata(tokenId, networkId, get(network) as INetwork)
-        } catch {
-            // do nothing
+            let isErc20Token = true
+            try {
+                validateEthereumAddress(tokenId)
+            } catch {
+                isErc20Token = false
+            }
```
Comment (MarkNerdi) [inline packages/shared/src/lib/core/token/actions/requestPersistedToken.ts]: extract into function

**Review by MarkNerdi — APPROVED** [review]
