### PR TITLE
enhancement: polish campaign leaderboard

### LINKED ISSUE #1844: ️🛠 - Polish campaign leaderboard
### Task description

- Fix padding in the bottom of the page
- Fix bottom row unexpected expanding
- Align badges
- Switch ordering of badges
- Increase length of address when needed

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary

closes #1844 

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [x] Windows

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/dashboard/campaigns/components/Leaderboard.svelte [hunk 1]
```diff
@@ -24,57 +24,91 @@
...
+                    {@const user = getSubjectFromAddress(leaderboardItem.address, networkId)}
+                    <tr class="w-full grid items-center gap-16 py-3 px-5">
+                        <td class="flex flex-row items-center justify-start gap-2">
+                            {#if index <= 2}
+                                <Avatar
+                                    icon={IconName.Award}
+                                    customTextColor={top3Colors[index]}
+                                    backgroundColor="surface/00"
+                                />
+                            {:else if user?.type === 'account'}
```
Comment (MarkNerdi) [inline packages/desktop/views/dashboard/campaigns/components/Leaderboard.svelte]:
```suggestion
                            {:else if leaderboardItem.address === userAddress}
```

**Review by MarkNerdi — APPROVED** [review]
