### PR TITLE
fix: check ERC721 media mimetype against whitelist instead of expected type

### LINKED ISSUE #1684: ️🛠 - Check ERC721 media mimetype against whitelist instead of expected type
### Task description

The erc721 metadata does not contain an expected mime type in all cases, so to makesure we are compatible we should just check the mimetype against a supported list.

### Requirements

Update checks to check against an array of supported mime types

### PR DESCRIPTION
**Pull request by nicole-obrien**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/nfts/actions/downloadNextNftInQueue.ts [hunk 1]
```diff
@@ -137,9 +144,19 @@ function isFileTooLarge(contentLength: string): boolean {
 }
 
 function isExpectedContentType(nft: INft, downloadMetadata: DownloadMetadata): boolean {
-    if (!nft.metadata?.type || !downloadMetadata.contentType) {
+    if (!downloadMetadata.contentType) {
         return false
     }
 
-    return downloadMetadata.contentType === String(nft.metadata.type)
+    if (isIrc27Nft(nft)) {
```
Comment (MarkNerdi) [inline packages/shared/src/lib/core/nfts/actions/downloadNextNftInQueue.ts]:
```suggestion
    if (isErc721Nft(nft)) {
```

**Review by MarkNerdi — APPROVED** [review]
LGTM
