### PR TITLE
Fix: layer1 to layer2

### LINKED ISSUE #860: ️🛠 - Support mainnet ShimmerEVM
### Task description

Update the app, so mainnet Shimmer EVM is supported. The following things need to be updated:

- [ ] Decide if we need different colors for Shimmer EVM & Shimmer EVM Testnet
- [ ] Decide if we need different tokens
- [ ] Explorer URL
- [ ] Updated Coin Types
- [ ] Alias Address
- [ ] Remove hardcoded ShimmerEvmTestnet

### Requirements

- [ ] L1 > L2
- [ ] L2 Token transfers
- [ ] L2 > L1

### PR DESCRIPTION
**Pull request by Tuditi**
## Summary

closes: https://github.com/bloomwalletio/bloom/issues/860

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/layer-2/actions/getLayer2MetadataForTransfer.ts [hunk 1]
```diff
@@ -5,17 +5,26 @@ import { SpecialStream } from '../classes'
...
-    const encodedAddress = address ? encodeAddress(address.toLowerCase()) : ''
+    const address = sendFlowParameters.recipient?.address ?? ''
+    const encodedAddress = encodeAddress(address.toLowerCase(), chain)
 
     const estimatedGas = await estimateGasForLayer1ToLayer2Transaction(sendFlowParameters as TokenSendFlowParameters)
     const gasLimit = Math.floor(estimatedGas * GAS_LIMIT_MULTIPLIER)
 
-    metadataStream.writeUInt32('senderContract', EXTERNALLY_OWNED_ACCOUNT)
+    // TODO: use writeUInt8 once EVM Testnet encoding reaches parity with ShimmerEVM
+    if (chainId === EvmChainId.ShimmerEvmTestnet) {
```
Comment (MarkNerdi) [inline packages/shared/src/lib/core/layer-2/actions/getLayer2MetadataForTransfer.ts]: just heads up: in this case it isnt that important as we won't support custom chains in the near future (and hopefully before they update the testnet), but it is always more future proof to use `chain.id === SupportedNetworkId.ShimmerEvmTestnet` as the chainId isnt unique across different netowrks (sui, eth, iota etc)

**Review by MarkNerdi — DISMISSED** [review]

**Review by MarkNerdi — APPROVED** [review]
