### PR TITLE
fix: inaccurate insufficient funds error

### LINKED ISSUE #648: ️🛠 - Insufficient funds error on network selection
### Task description

If the user accesses the network/recipient selection the first time, they always get 
image

The reason maybe is, that we only start polling the gas on the `SelectTokenView`. 

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by maxwellmattryan**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

This PR fixes an issue that was caused from beginning the polling for gas price too late by querying the (fixed as of now) gas price once during login.

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/layer-2/actions/updateEvmChainGasPrice.ts [hunk 1]
```diff
@@ -2,14 +2,24 @@ import { handleError } from '@core/error/handlers'
...
         handleError(err)
     }
 }
+
+export async function updateEvmChainGasPrices(networkIds?: NetworkId[]): Promise<void> {
+    const profileChainIds =
+        getNetwork()
+            ?.getChains()
+            ?.map((chain) => chain.getConfiguration().id) ?? []
+    const chainsToQuery = networkIds ? networkIds : profileChainIds
```
Comment (MarkNerdi) [inline packages/shared/src/lib/core/layer-2/actions/updateEvmChainGasPrice.ts]: i think we can for now remove the parameter, as it is not needed

**Review by MarkNerdi — APPROVED** [review]
LGTM
