### PR TITLE
fix: duplicated nft balance change activities

### LINKED ISSUE #1706: ️🛠 - Fix duplicated NFT balance change activities
### Task description

_No response_

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-2-to-3.ts [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+    })
+
+    profiles.update((state) => {
+        const profileIndex = state.findIndex((p) => p.id === profile.id)
+        const _profile = state[profileIndex]
+        if (!_profile) {
+            return state
+        }
+
+        for (const networkId of Object.keys(_profile.trackedNfts)) {
```
Comment (Tuditi) [inline packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-2-to-3.ts]: I'm getting errors here:

```
checkAndMigrateProfiles.ts:27 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at alpha-profile-migration-5-to-6.ts:70:1
    at Object.update (index.mjs:42:1)
    at Object.alphaProfileMigration5To6 (alpha-profile-migration-5-to-6.ts:63:1)
    at checkAndMigrateProfiles.ts:22:1
    at Generator.next (<anonymous>)
    at index.ts:3:1
    at new Promise (<anonymous>)
    at __async (index.ts:3:1)
    at migratePersistedProfiles (checkAndMigrateProfiles.ts:15:1)
```

File: packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-5-to-6.ts
Comment (Tuditi) [inline packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-5-to-6.ts:1]: We should not duplicate the alpha and prod migration.

**Review by Tuditi — CHANGES_REQUESTED** [review]
I left some comments. My activity list shows this duplicate activity for L2 -> L1 NFT transfers. Is this expected?

File: packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-5-to-6.ts
Comment (MarkNerdi) [reply packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-5-to-6.ts:1]: i think there is no better way. If we would have a new alpha migration, we would put that into a new `alpha-migration` file, but in the same old file `prod-migration` file as that file combines all migrations for the new version.

 creating an external file for this logic would be redundant IMO because this file should not be touched afterwards and is only relevant for these 2 functions

**Review by Tuditi — APPROVED** [review]
LGTM!
