### PR TITLE
fix: fix account summary reactivity

### LINKED ISSUE #788: ️🛠 - Fix content height of account network summary
### Task description

Fix content height of account network summary if the balance is 0

image

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts [hunk 1]
```diff
@@ -64,6 +64,7 @@ export function getTransactionAssets(
     } else if (activity.type === ActivityType.Alias) {
         return {
             aliasId: activity.aliasId,
+            baseCoinTransfer: activity.action !== ActivityAction.Burn ? baseCoinTransfer : undefined,
```
Comment (Tuditi) [inline packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts]: Maybe this can be moved to line 26, so you don't have these duplications?

File: packages/shared/src/locales/en.json [hunk 2]
```diff
@@ -1884,7 +1884,8 @@
             "degraded": "Degraded",
             "operational": "Operational",
             "disconnected": "Disconnected"
-        }
+        },
+        "smartContract": "Smart Contract"
```
Comment (Tuditi) [inline packages/shared/src/locales/en.json]: We already have a locale for smart contract. I think it's okay to use it inside ActivityStatusPills.

**Review by Tuditi — CHANGES_REQUESTED** [review]
Works well! Requested some minor code changes.

File: packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts (hunk 1 above)
Comment (MarkNerdi) [reply packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts]: fixed in dedicated PR

**Review by Tuditi — APPROVED** [review]
LGTM! :fire:
