### PR TITLE
Fix: insufficient funds

### LINKED ISSUE #1083: :lady_beetle:  - Fix insufficient funds error when sending all outputs from stronghold
### Task description

Sending with Ledger/Stronghold results in an insufficient fund error if you return to the confirm pop-up when sending a layer 1 transaction.

Steps to reproduce:

With Stronghold profile

1.     Lock Stronghold
2.     Send all your SMR funds on L1
3.     Input Password
4.     Confirm Page
5.     See insufficient fund bugs

### Requirements

TBD

### PR DESCRIPTION
**Pull request by Tuditi**
## Summary

closes: https://github.com/bloomwalletio/bloom/issues/1083

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/components/popup/popups/SendFlowPopup.svelte [hunk 1]
```diff
@@ -1,9 +1,15 @@
...
+    import { EvmTransactionData } from '@core/layer-2/types'
+    import { Output } from '@core/wallet/types'
     import { SendFlowRouterView } from '@views/dashboard/send-flow'
 
-    export let _onMount: (..._: any[]) => Promise<void> = async () => {}
+    export let _onMount: (..._: any[]) => Promise<void> = undefined
+    export let preparedOutput: Output | undefined = undefined
+    export let preparedTransaction: EvmTransactionData | undefined = undefined
+
+    const transactionSummaryProps = { _onMount, preparedOutput, preparedTransaction }
```
Comment (MarkNerdi) [inline packages/desktop/components/popup/popups/SendFlowPopup.svelte:10]: whats the point of combining those props into an object, and then immediatly deconstruct them again in the child?

Comment (Tuditi) [reply packages/desktop/components/popup/popups/SendFlowPopup.svelte:10]: It makes the code cleaner. Otherwise, I have to pass in 3 props to the `SendFlowRouterView`, which has nothing to do with `TransactionSummaryView`. This way it's more extendable if we would need to add an extra component in the flow or an extra property.

**Review by MarkNerdi — APPROVED** [review]
