### PR TITLE
fix: alignment if NFT with space as name

### LINKED ISSUE #1886: ️🛠 - Fix alignment if NFT with space as name
### Task description

If we mint an NFT with a space, the alignment is messed up.

image

### Requirements

TBD

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary

closes #1886 

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [x] Windows

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/components/molecules/NftGalleryItem.svelte [hunk 1]
```diff
@@ -67,7 +67,7 @@
     </div>
     <div class="flex flex-col gap-2 p-3">
         <nft-name class="w-full flex flex-row items-center justify-between gap-2">
-            <Text type="body2" truncate>{nft.name}</Text>
+            <Text type="body2" truncate class="after:content-['\200b']">{nft.name}</Text>
```
Comment (MarkNerdi) [inline packages/shared/src/components/molecules/NftGalleryItem.svelte:70]: can we not just give each TextType a `lineheight` to prevent shrinking?

Comment (jeeanribeiro) [reply packages/shared/src/components/molecules/NftGalleryItem.svelte:70]: We already have line height in each text type, but it doesn't prevent shrinking

**Review by MarkNerdi — APPROVED** [review]

**Review by MarkNerdi — APPROVED** [review]
