### PR TITLE
fix: get correct subject for evm addresses

### LINKED ISSUE #603: ️🛠 - Show account/contact as subject for L1->L2 and L2->L1
### Task description

_No response_

### Requirements

_No response_

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/src/lib/core/activity/utils/helper/index.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ export * from './getGovernorAddressFromAliasOutput'
 export * from './getMetadataFromOutput'
 export * from './getStateControllerAddressFromAliasOutput'
 export * from './getStorageDepositFromOutput'
-export * from './getSubjectFromActivity'
+export * from './getSubjectLocaleFromActivity'
```
Comment (maxwellmattryan) [inline packages/shared/src/lib/core/activity/utils/helper/index.ts:11]: Does this filename match the function?

Comment (MarkNerdi) [reply packages/shared/src/lib/core/activity/utils/helper/index.ts:11]: yes it does

**Review by maxwellmattryan — APPROVED** [review]
LGTM :cherry_blossom:
